version: '3.8'

services:
  db:
    image: postgres:13
    container_name: go-pvz-db
    environment:
      POSTGRES_DB: go_pvz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
